<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>NBXplorer.Fuzz</AssemblyName>
    <RootNamespace>NBXplorer.Fuzz</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SharpFuzz" Version="2.3.0" />
    <ProjectReference Include="../NBXplorer/NBXplorer.csproj" />
  </ItemGroup>

</Project>
