using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using NBitcoin;
using NBXplorer.Configuration;
using Xunit;

namespace NBXplorer.Tests;

[Collection("Console output")]
public class DocumentationTests
{
	private static readonly (string Title, HashSet<string> Names)[] ConfigurationCategories =
	[
		("Process and network", ["help", "network", "chains", "conf", "port", "bind", "datadir"]),
		("Database", ["postgres"]),
		("HTTP and authentication", ["noauth", "instancename", "exposerpc"]),
		("Wallet tracking and scanning", ["nowarmup", "customkeypathtemplate", "maxgapsize", "mingapsize", "trimevents"]),
		("Logging and diagnostics", ["signalfilesdir", "verbose"])
	];
	private static readonly HashSet<string> UndocumentedOptions =
	[
		"testnet", "regtest", "signet", "socksendpoint", "socksuser", "sockspassword"
	];

	private static readonly string[] ChainOptionSuffixes =
	[
		"rescan", "rescaniftimebefore", "rpcuser", "rpcdefaultwallet", "rpcpassword", "rpccookiefile",
		"rpcauth", "rpcurl", "startheight", "minutxovalue", "nodeendpoint", "exposerpc"
	];

	[Fact]
	public void ConfigurationReferenceMatchesCommandLineOptions()
	{
		var repositoryRoot = MaintenanceUtilities.TryGetSolutionDirectoryInfo().FullName;
		var outputPath = Path.Combine(repositoryRoot, "docs", "configuration-reference.md");
		var errors = new List<string>();
		var generatedReference = GenerateConfigurationReference(errors);

		if (generatedReference is not null &&
			(!File.Exists(outputPath) || NormalizeLineEndings(File.ReadAllText(outputPath)) != generatedReference))
		{
			var updateReference = Environment.GetEnvironmentVariable("UPDATE_CONFIGURATION_REFERENCE") == "1";
			if (updateReference)
				File.WriteAllText(outputPath, generatedReference);
			errors.Add(updateReference
				? "docs/configuration-reference.md was stale and has been updated. Review and commit it, then rerun this test."
				: "docs/configuration-reference.md is stale. Set UPDATE_CONFIGURATION_REFERENCE=1 to update it, then rerun this test.");
		}

		Assert.True(errors.Count == 0, string.Join(Environment.NewLine, errors));
	}

	private static string GenerateConfigurationReference(List<string> errors)
	{
		var options = GetCommandLineOptions(errors);
		if (options is null)
			return null;

		var cryptoCodes = new NBXplorerNetworkProvider(ChainName.Mainnet).GetAll()
			.Select(network => network.CryptoCode.ToLowerInvariant())
			.ToArray();
		var globalNames = ConfigurationCategories.SelectMany(category => category.Names).ToHashSet();
		var chainOptions = options.Where(option => TryGetChainOption(option.Name, cryptoCodes, out _, out _)).ToArray();
		var unknown = options.Where(option => !globalNames.Contains(option.Name) &&
											!UndocumentedOptions.Contains(option.Name) &&
											!chainOptions.Contains(option)).Select(option => option.Name).ToArray();
		var missing = globalNames.Where(name => options.All(option => option.Name != name)).ToArray();

		if (unknown.Length > 0)
			errors.Add($"Uncategorized options: {string.Join(", ", unknown)}");
		if (missing.Length > 0)
			errors.Add($"Missing options: {string.Join(", ", missing)}");

		foreach (var cryptoCode in cryptoCodes)
		{
			var suffixes = chainOptions
				.Where(option => option.Name.StartsWith(cryptoCode, StringComparison.Ordinal))
				.Select(option => option.Name[cryptoCode.Length..])
				.ToHashSet();
			var missingSuffixes = ChainOptionSuffixes.Where(suffix => !suffixes.Contains(suffix)).ToArray();
			var unknownSuffixes = suffixes.Where(suffix => !ChainOptionSuffixes.Contains(suffix)).ToArray();
			if (missingSuffixes.Length > 0)
				errors.Add($"Missing {cryptoCode.ToUpperInvariant()} options: {string.Join(", ", missingSuffixes)}");
			if (unknownSuffixes.Length > 0)
				errors.Add($"Unknown {cryptoCode.ToUpperInvariant()} options: {string.Join(", ", unknownSuffixes)}");
		}

		if (errors.Count > 0)
			return null;

		var sections = ConfigurationCategories.Select(category =>
		{
			var rows = options.Where(option => category.Names.Contains(option.Name)).Select(ConfigurationRow);
			return $"## {category.Title}\n\n| Command line | Configuration file | Environment | Description |\n|---|---|---|---|\n{string.Join("\n", rows)}";
		});
		var bitcoinOptions = chainOptions.Where(option => option.Name.StartsWith("btc", StringComparison.Ordinal)).ToArray();
		var chainRows = ChainOptionSuffixes.Select(suffix =>
		{
			var option = bitcoinOptions.Single(option => option.Name == $"btc{suffix}");
			return ChainConfigurationRow(suffix, option.Description.Replace("--btc", "--&lt;crypto&gt;", StringComparison.Ordinal));
		});

		return "# Configuration reference\n\n" +
			   "<!-- Generated by DocumentationTests. Do not edit manually. -->\n\n" +
			   "This reference is generated from every command-line option registered by the\n" +
			   "standard build of NBXplorer. Use the same application version that you deploy\n" +
			   "because options and defaults can change between releases.\n\n" +
			   "Configuration-file keys, environment variables, and command-line options feed\n" +
			   "the same configuration system. Environment variables use the `NBXPLORER_`\n" +
			   "prefix. Run `NBXplorer --help` to inspect the deployed version directly.\n\n" +
			   string.Join("\n\n", sections) + "\n\n" +
			   "## Chain-specific node and RPC settings\n\n" +
			   "Replace `<crypto>` with a lowercase code in command-line and configuration-file\n" +
			   "settings, and replace `<CRYPTO>` with its uppercase code in environment\n" +
			   "variables. For example, Bitcoin's RPC URL is `--btcrpcurl`, `btc.rpc.url`,\n" +
			   "or `NBXPLORER_BTCRPCURL`. The `minutxovalue` setting does not apply to\n" +
			   "Liquid (`LBTC`).\n\n" +
			   $"Supported codes in this build: {string.Join(", ", cryptoCodes.Select(code => $"`{code.ToUpperInvariant()}`"))}.\n\n" +
			   "| Command line | Configuration file | Environment | Description |\n" +
			   "|---|---|---|---|\n" +
			   string.Join("\n", chainRows) + "\n";
	}

	private static List<ConfigurationOption> GetCommandLineOptions(List<string> errors)
	{
		var originalOutput = Console.Out;
		var originalError = Console.Error;
		using var output = new StringWriter();
		try
		{
			Console.SetOut(output);
			Console.SetError(output);
			new DefaultConfiguration().CreateConfigurationBuilder(["--help"]);
		}
		finally
		{
			Console.SetOut(originalOutput);
			Console.SetError(originalError);
		}

		var help = Regex.Replace(output.ToString(), "\u001b\\[[0-9;]*m", string.Empty);
		if (!help.Contains("Usage: NBXplorer [options]", StringComparison.Ordinal))
		{
			errors.Add("Could not read NBXplorer command-line help.");
			return null;
		}

		var options = new List<ConfigurationOption>();
		var inOptions = false;
		foreach (var line in Regex.Split(help, "\r?\n"))
		{
			if (line == "Options:")
			{
				inOptions = true;
				continue;
			}
			if (!inOptions || !line.StartsWith("  ", StringComparison.Ordinal))
				continue;

			var match = Regex.Match(line, @"^\s{2}(.+?)\s{2,}(.+)$");
			if (!match.Success)
				continue;
			var syntax = match.Groups[1].Value.Trim();
			var names = Regex.Matches(syntax, @"--([a-z0-9-]+)", RegexOptions.IgnoreCase);
			if (names.Count > 0)
				options.Add(new ConfigurationOption(names[0].Groups[1].Value, syntax, match.Groups[2].Value.Trim()));
		}
		return options;
	}

	private static bool TryGetChainOption(string name, string[] cryptoCodes, out string cryptoCode, out string suffix)
	{
		cryptoCode = cryptoCodes.FirstOrDefault(code => name.StartsWith(code, StringComparison.Ordinal));
		suffix = cryptoCode is null ? null : name[cryptoCode.Length..];
		return cryptoCode is not null;
	}

	private static string ConfigurationRow(ConfigurationOption option)
	{
		var configuration = option.Name == "help" ? "N/A" : $"`{option.Name}`";
		var environment = option.Name == "help" ? "N/A" : $"`NBXPLORER_{option.Name.ToUpperInvariant()}`";
		return $"| `{EscapeCell(option.Syntax)}` | {configuration} | {environment} | {EscapeCell(option.Description)} |";
	}

	private static string ChainConfigurationRow(string suffix, string description)
	{
		return $"| `--<crypto>{suffix}` | `<crypto>.{ChainConfigurationKey(suffix)}` | `NBXPLORER_<CRYPTO>{suffix.ToUpperInvariant()}` | {EscapeCell(description)} |";
	}

	private static string ChainConfigurationKey(string suffix)
	{
		return suffix switch
		{
			"rpcuser" => "rpc.user",
			"rpcdefaultwallet" => "rpc.defaultwallet",
			"rpcpassword" => "rpc.password",
			"rpccookiefile" => "rpc.cookiefile",
			"rpcauth" => "rpc.auth",
			"rpcurl" => "rpc.url",
			"nodeendpoint" => "node.endpoint",
			_ => suffix
		};
	}

	private static string EscapeCell(string value)
	{
		return value.Replace("|", "\\|", StringComparison.Ordinal);
	}

	private static string NormalizeLineEndings(string value)
	{
		return value.Replace("\r\n", "\n", StringComparison.Ordinal);
	}

	private sealed record ConfigurationOption(string Name, string Syntax, string Description);
}

[CollectionDefinition("Console output", DisableParallelization = true)]
public sealed class ConsoleOutputCollection;
